/* ADAM/DS — scramble/meta · chars + fonts + voices · [plan:2026-09-13_193000-refactor-manageability.md#phase-2] */
// Exports: CHARS, FONT_STYLES, VOICES
const CHARS = {
  upperCase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  lowerCase: 'abcdefghijklmnopqrstuvwxyz',
  upperAndLowerCase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
  numbers: '0123456789',
 XO: 'XO',
  symbols: '!<>-_\\/[]{}—=+*^?#',
  custom: ''
};
const FONT_STYLES = {
  display: { label: 'Display · --text-display',
    size: 'var(--text-display)',
    leading: 'var(--leading-display)',
    tracking: 'var(--tracking-display)',
    weight: '700',
    family: 'var(--font-sans)' },
  title: { label: 'Title · --text-title',
    size: 'var(--text-title)',
    leading: 'var(--leading-title)',
    tracking: 'var(--tracking-title)',
    weight: '700',
    family: 'var(--font-sans)' },
  logo: { label: 'Logo · --text-logo',
    size: 'var(--text-logo)',
    leading: 'var(--leading-display)',
    tracking: 'var(--tracking-display)',
    weight: '700',
    family: 'var(--font-sans)' },
  h2: { label: 'Section h2 · --text-h2',
    size: 'var(--text-h2)',
    leading: 'var(--leading-snug)',
    tracking: 'var(--tracking-heading)',
    weight: '700',
    family: 'var(--font-sans)' },
  card: { label: 'Card title · --text-card-title',
    size: 'var(--text-card-title)',
    leading: 'var(--leading-snug)',
    tracking: 'var(--tracking-body)',
    weight: '600',
    family: 'var(--font-sans)' },
  h3: { label: 'Section h3 · --text-h3',
    size: 'var(--text-h3)',
    leading: 'var(--leading-snug)',
    tracking: 'var(--tracking-heading)',
    weight: '600',
    family: 'var(--font-sans)' },
  body: { label: 'Body · --text-body',
    size: 'var(--text-body)',
    leading: 'var(--leading-body)',
    tracking: 'var(--tracking-body)',
    weight: '400',
    family: 'var(--font-sans)' },
  small: { label: 'Small · --text-small',
    size: 'var(--text-small)',
    leading: 'var(--leading-snug)',
    tracking: 'var(--tracking-body)',
    weight: '600',
    family: 'var(--font-sans)' },
  meta: { label: 'Mono Meta · --text-meta',
    size: 'var(--text-meta)',
    leading: 'var(--leading-mono)',
    tracking: 'var(--tracking-mono)',
    weight: '500',
    family: 'var(--font-mono)' },
  label: { label: 'Label · --text-label',
    size: 'var(--text-label)',
    leading: 'var(--leading-mono)',
    tracking: 'var(--tracking-label)',
    weight: '500',
    family: 'var(--font-mono)' },
  micro: { label: 'Micro · --text-micro',
    size: 'var(--text-micro)',
    leading: 'var(--leading-mono)',
    tracking: 'var(--tracking-mono)',
    weight: '500',
    family: 'var(--font-mono)' },
};
const VOICES = ['random','tick','static','blip','chime','hum','data','scanner','zap','zapscan'];
export { CHARS, FONT_STYLES, VOICES };
