/* ADAM/DS — ds/component/knobs · knob controls · [plan:2026-09-13_193000-refactor-manageability.md#phase-3] */
export function knobsHTML(knobs, id){return knobs.map((k)=>{
    if(k.type==='select') return [
      `<label class="fx-row">`,
      k.label,
      ` <select data-k="`,
      k.key,
      `" data-comp="`,
      id,
      `">`,
      k.options.map((o)=>[
        `<option value="`,
        o.value,
        `"`,
        o.value===k.default?' selected':'',
        `>`,
        o.label,
        `</option>`,
      ].join('')).join(''),
      `</select><output data-v="`,
      k.key,
      `">`,
      k.default,
      `</output></label>`,
    ].join('');
    if(k.type==='range') return [
      `<label class="fx-row">`,
      k.label,
      ` <input type="range" min="`,
      k.min,
      `" max="`,
      k.max,
      `" step="`,
      k.step,
      `" value="`,
      k.default,
      `" data-k="`,
      k.key,
      `" data-comp="`,
      id,
      `"><output data-v="`,
      k.key,
      `">`,
      k.default,
      k.unit||'',
      `</output></label>`,
    ].join('');
    return [
      `<label class="fx-row">`,
      k.label,
      ` <input type="checkbox" `,
      k.default?'checked':'',
      ` data-k="`,
      k.key,
      `" data-comp="`,
      id,
      `"><output data-v="`,
      k.key,
      `">`,
      k.default?'on':'off',
      `</output></label>`,
    ].join('');
  }).join('');}
