/* ADAM/DS — overview/hero.js · hero markup · [plan:2026-09-13_193000-refactor-manageability.md#phase-3] */
export function heroHtml(y) {
  return [
    `<div class="lc-hero"><div class="lc-hero-cross" aria-hidden="true"></div><div class="lc-hero-ink">`,
    `<div class="lc-eyebrow">00 <span class="slash">//</span> OVERVIEW — ADAM/DS</div><h1>`,
    `<span>LOSS<em class="dash">—</em></span><span>LESS</span>`,
    `<span class="cyberpunk">CYBERPUNK<i class="dot neutral">.</i></span></h1>`,
    `<p class="lede">Everything gets compressed now — feeds, files, days. Most of it loses something on the way `,
    `down. This system is built the other way: keep cutting until only the meaning is left, and make sure that part `,
    `arrives intact.</p><div class="lc-status" style="margin-top:var(--space-16)"><i>lossless <b>vector</b></i>`,
    `<i>radius <b>0</b></i><i>signal <b>once</b></i><i>build <b>✓</b></i></div>`,
    `<div class="lc-dots-h" aria-hidden="true"></div></div><div class="lc-hero-paper">`,
    `<canvas class="lc-orb" data-lc-orb aria-hidden="true"></canvas>`,
    `<div style="display:flex; justify-content:space-between; align-items:flex-start; gap:var(--space-12);">`,
    `<div class="lc-eyebrow" style="color:var(--color-ink-muted)">01 // STYLE</div><div class="lc-meta-row">`,
    `<a class="lc-corner-btn" href="#/foundations" style="text-decoration:none">Explore<i></i></a>`,
    `<a class="lc-corner-btn is-ink" href="#/foundations" aria-label="Play" style="text-decoration:none; `,
    `width:44px; height:44px; padding:0; justify-content:center;">▶<i></i></a></div></div><div>`,
    `<p class="lede">Lossless is the edit — nothing left that can go. Cyberpunk is the mood — black ground, hard `,
    `cuts, one red signal in the dark. Six refs below, one lesson each, images in <span `,
    `class="tok">/images/mood</span>.</p>`,
    `<p class="lede" style="margin-top:var(--space-10); font-family:var(--font-mono); font-size:10px; `,
    `letter-spacing:var(--tracking-mono); text-transform:uppercase; color:var(--color-ink-muted); `,
    `opacity:0.9">MATERIAL — <span class="tok" style="color:var(--color-ink)">Frost Alloy</span> hull + <span `,
    `class="tok" style="color:var(--color-accent)">Signal Phosphor</span> on cool void · Caution Resin + Circuit `,
    `Glass — synthetic, never real matter</p>`,
    `<div style="display:flex; gap:var(--space-8); margin-top:var(--space-14); flex-wrap:wrap; position:relative; `,
    `z-index:1;"><span class="tok">Inter Tight 700</span><span class="tok">Chivo Mono 500</span>`,
    `<span class="tok">--color-accent #E8442E</span><span class="tok">--radius-0</span></div></div>`,
    `<div class="lc-red-cut" data-edition="redux" aria-hidden="true"><span>REDUX `,
    y,
    `</span></div></div></div>`,
  ].join('');
}
