/* ADAM/DS — overview/mood.js · moodboard markup · [plan:2026-09-13_193000-refactor-manageability.md#phase-3] */
export function moodHtml() {
  return [
    `<div class="ds-sec" style="position:relative; overflow:visible;">`,
    `<div style="display:flex; align-items:baseline; gap:var(--space-12); flex-wrap:wrap;">`,
    `<h2 style="margin:0">Moodboard</h2>`,
    `<span class="kicker" style="color:var(--color-ink-muted)">Lossless Cyberpunk — 6 refs · editorial freeform · `,
    `12-col · fetched</span></div>`,
    `<p class="sub" style="max-width:62ch">Six refs, not project thumbs. Hover brings back the colour. Pure <span `,
    `class="tok">var()</span>, zero radius, hairline only.</p>`,
    `<div class="lc-over-dots" style="right:-10px; top:42px; width:64px; height:96px;" aria-hidden="true"></div>`,
    `<div class="lc-over-dots" style="left:-8px; bottom:18px; width:96px; height:44px; opacity:0.1" `,
    `aria-hidden="true"></div><div class="lc-mood">`,
    `<div class="lc-tile chamfer is-signal" style="grid-column:span 7;"><span class="img" style="height:248px">`,
    `<img src="/images/mood/neon-void.jpg" alt="Neon street at night — one signal in the void" loading="lazy" />`,
    `</span><div class="body"><div class="kicker"><b>01</b> Neon void — signal in the black</div>`,
    `<div class="title">One signal on cold void — accent only as alert.</div><p class="copy">`,
    `<a href="https://bladerunner2049.warnerbros.com" target="_blank" rel="noopener">Blade Runner 2049 — neon on `,
    `black</a> — what we steal: monochrome ground, single accent-500; no gradients. Photo · Unsplash.</p>`,
    `<div class="meta"><span>fetched · neon-void</span><span>span 7</span></div></div></div>`,
    `<div class="lc-tile" style="grid-column:span 5;"><span class="img" style="height:248px">`,
    `<img src="/images/mood/hard-grid.jpg" alt="Musica Viva concert poster 1959 — Swiss grid geometry" `,
    `loading="lazy" /></span><div class="body"><div class="kicker"><b>02</b> Hard grid — geometry carries it</div>`,
    `<div class="title">Absolute grid, 90° cuts only — no ornament.</div><p class="copy">`,
    `<a href="https://www.lars-mueller-publishers.com/josef-muller-brockmann" target="_blank" `,
    `rel="noopener">Müller-Brockmann · Musica Viva 1959</a> — what we steal: hairline as the only elevation. Poster `,
    `· Wikimedia Commons.</p><div class="meta"><span>fetched · hard-grid</span><span>span 5</span></div></div></div>`,
    `<div class="lc-tile accent-left tilt" style="grid-column:span 4;"><span class="img" style="height:208px">`,
    `<img src="/images/mood/one-signal.jpg" alt="Retro terminal console — mono signal" loading="lazy" /></span>`,
    `<div class="body"><div class="kicker"><b>03</b> One signal — mono machine</div>`,
    `<div class="title">Console order — mono, dense, precise.</div><p class="copy">`,
    `<a href="https://www.are.na" target="_blank" rel="noopener">Are.na / Cyberpunk console</a> — steal: single `,
    `accent sparingly; chrome stays ink + line. Photo · Unsplash.</p><div class="meta"><span>tilt -0.6°</span>`,
    `<span>accent left</span></div></div></div>`,
    `<div class="lc-tile chamfer" style="grid-column:span 4; border-left:var(--size-frame) solid var(--color-ink);">`,
    `<span class="img" style="height:208px">`,
    `<img src="/images/mood/brutal-shell.jpg" alt="Braun ET66 calculator by Dieter Rams" loading="lazy" /></span>`,
    `<div class="body" style="background:var(--color-ink); color:var(--color-bg);">`,
    `<div class="kicker" style="color:var(--color-bg)">`,
    `<b style="color:var(--color-accent)">04</b> Brutal shell — less but better</div>`,
    `<div class="title" style="color:var(--color-bg)">Radius 0 by doctrine — form is function.</div>`,
    `<p class="copy" style="color:color-mix(in srgb, var(--color-bg) 70%, transparent)">`,
    `<a href="https://www.vitsoe.com/us/about/good-design" target="_blank" rel="noopener" `,
    `style="color:var(--color-bg); border-color:color-mix(in srgb, var(--color-bg) 30%, transparent)">Dieter Rams · `,
    `Braun ET66, 1987</a> — steal: brutal hard-case shell, no ornament. Photo · CC BY-SA 2.0 Wikimedia.</p>`,
    `<div class="meta" style="color:color-mix(in srgb, var(--color-bg) 60%, transparent); border-color:color-mix(in `,
    `srgb, var(--color-bg) 18%, transparent)"><span>ink invert</span><span>chamfer</span></div></div></div>`,
    `<div class="lc-tile" style="grid-column:span 4;"><span class="img" style="height:208px">`,
    `<img src="/images/mood/system-docs.jpg" alt="Dark code editor — terminal as product" loading="lazy" /></span>`,
    `<div class="body"><div class="kicker"><b>05</b> System docs — terminal as product</div>`,
    `<div class="title">Foundations → Tokens → Components → Patterns.</div><p class="copy">`,
    `<a href="https://linear.app" target="_blank" rel="noopener">Linear — docs as product</a> — steal: console `,
    `order; mono, dense, precise. Photo · Unsplash.</p><div class="meta"><span>fetched · system-docs</span>`,
    `<span>span 4</span></div></div></div><div class="lc-tile tilt" style="grid-column:span 8;">`,
    `<span class="img" style="height:228px">`,
    `<img src="/images/mood/paper-terrain.jpg" alt="White architectural model — paper relief terrain" `,
    `loading="lazy" /></span><div class="body"><div class="kicker"><b>06</b> Paper terrain — lossless relief</div>`,
    `<div class="title">Volume from paper, depth from a hard edge.</div>`,
    `<p class="copy">From your moodboard ref — white terrain, contour paper, city relief. What we steal: monochrome `,
    `volume, hard-cut base, hairline contour. Depth is an edge, never a shadow.</p><div class="meta">`,
    `<span>fetched · paper-terrain</span><span>span 8 · tilt</span></div></div></div>`,
    `<div class="lc-tile" style="grid-column:1 / -1; flex-direction:row; align-items:stretch; min-height:96px; `,
    `border-style:dashed;">`,
    `<div style="flex:1 1 52%; padding:var(--space-12) var(--space-14); display:grid; gap:var(--space-8); `,
    `align-content:center; border-right:var(--border-hairline);"><div class="kicker">`,
    `<b>07</b> Spec — lossless tokens</div><div class="lc-specbar">`,
    `<i style="background:var(--color-accent); color:var(--color-on-accent);">#E8442E <span `,
    `style="opacity:0.8">accent-500</span></i>`,
    `<i style="background:var(--color-ink); color:var(--color-bg);">#15191f <span style="opacity:0.6">ink</span></i>`,
    `<i style="background:var(--color-bg); color:var(--color-ink);">#eceef2 <span style="opacity:0.6">paper</span>`,
    `</i>`,
    `<i style="background:var(--stone-200); color:var(--color-ink);">#e2e6ea <span style="opacity:0.6">sunken</span>`,
    `</i></div>`,
    `<div class="copy" style="margin-top:var(--space-4)">Type: <span class="tok">Inter Tight 700</span> + <span `,
    `class="tok">Chivo Mono 500</span> · Tracking <span class="tok">-0.04em</span> display · <span `,
    `class="tok">0</span> radius everywhere — editorial cut, not soft UI.</div></div>`,
    `<div style="flex:1 1 48%; padding:var(--space-12) var(--space-14); background:var(--color-panel); `,
    `display:grid; place-content:center; text-align:center;">`,
    `<div style="font-family:var(--font-mono); font-size:var(--text-micro); letter-spacing:var(--tracking-mono); `,
    `text-transform:uppercase; color:var(--color-ink-muted)">The test</div>`,
    `<div style="font-family:var(--font-sans); font-weight:var(--weight-bold); font-size:18px; `,
    `letter-spacing:-0.03em; margin-top:var(--space-6);">CUT UNTIL IT MEANS MORE</div>`,
    `<div style="font-family:var(--font-mono); font-size:10px; color:var(--color-ink-muted); `,
    `margin-top:var(--space-4)">If one more cut changes the meaning, stop</div></div></div></div>`,
    `<p class="vl" style="font-family:var(--font-mono); font-size:var(--text-micro); color:var(--color-ink-muted); `,
    `margin-top:var(--space-8)">Freeform on a 12-col grid — 7/5, then 4/4/4, one wide terrain. Images in <span `,
    `class="tok">/images/mood</span> — fetched refs, not thumbs.</p></div>`,
  ].join('');
}
