/* ADAM/DS — ds/foundations/motion/data · duration data · [plan:2026-09-13_193000-refactor-manageability.md#phase-3] */
const DURS = [['Fast', '--dur-fast', '6.8%'],
  ['Base', '--dur-base', '9.1%'],
  ['Med', '--dur-med', '10%'],
  ['Soft', '--dur-soft', '11.4%'],
  ['Slow', '--dur-slow', '12.7%'],
  ['Reveal', '--dur-reveal', '13.6%'],
  ['Glide', '--dur-glide', '17.3%'],
  ['Blur', '--dur-blur', '20.5%'],
  ['Zoom', '--dur-zoom', '29.5%'],
  ['Hero rise', '--dur-hero-rise', '39.1%'],
  ['Shimmer', '--dur-shimmer', '100%']];
const USES = [['Fast', '--dur-fast', '150ms · micro feedback — chip flip, toggle tick'],
  ['Base', '--dur-base', '200ms · control response — press, tab switch'],
  ['Med', '--dur-med', '220ms · small reveal — tooltip, menu'],
  ['Soft', '--dur-soft', '250ms · panel settle — popover nudge'],
  ['Slow', '--dur-slow', '280ms · card hover settle'],
  ['Reveal', '--dur-reveal', '300ms · content reveal — cell tint, viewer open'],
  ['Glide', '--dur-glide', '380ms · signature travel — frame, rise, dot'],
  ['Blur', '--dur-blur', '450ms · frost settle — header blur-in'],
  ['Zoom', '--dur-zoom', '650ms · image zoom settle'],
  ['Hero rise', '--dur-hero-rise', '860ms · hero entrance'],
  ['Shimmer', '--dur-shimmer', '2.2s · ambient skeleton sweep — freezable, stills under reduced motion'],
  ['FX color', '--dur-fx-color', '240ms · cell tint sweep — demo in FX'],
  ['FX span', '--dur-fx-span', '0.6s · cell sweep span — demo in FX'],
  ['Viewer in', '--dur-viewer-in', '300ms · viewer open — demo in FX viewer'],
  ['Viewer line', '--dur-viewer-line', '780ms · viewer tether draw — demo in FX viewer']];
const BLURS = [['Header frost', '--blur-header', 'sticky header over scroll'],
  ['Card scrim', '--blur-scrim', 'card scrim over photos'],
  ['Placeholder', '--blur-placeholder', 'image placeholder wash']];
export { DURS, USES, BLURS };
