/* DS change tracker — bidirectional plan ↔ execution links.
   Commits touching DS paths cite `[plan:<file>#<anchor>]`; this writes
   src/ds/changelog-manifest.json (auto on `npm run build`), rendered by
   pages-changelog.js. Never fails (keeps old manifest if git missing).
   Continuation: 20260909_145218_9888b1 — all future scopes branch from here. */
import { readdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src/ds/changelog-manifest.json');
const DS = ['src/ds', 'src/styles/tokens.css', 'DESIGN.md', 'design.md'];
const TAG = /\[plan:([^\]#\s]+)(?:#([^\]]+))?\]/;
const CONTINUATION = '20260909_145218_9888b1';
const sh = (cmd) => { try { return execSync(cmd, { cwd: root, encoding: 'utf8' }); } catch { return null; } };

const plans = readdirSync(join(root, '.hermes/plans')).filter((f) => f.endsWith('.md')).sort();
const read = (f) => { try { return readFileSync(join(root, '.hermes/plans', f), 'utf8'); } catch { return ''; } };
const phased = plans.filter((f) => /^## Phase /m.test(read(f)));
const tagged = phased.filter((f) => /^\*{1,2}Tags:/m.test(read(f).split(/^## /m)[0])).length;
const retro = (() => { try { return JSON.parse(readFileSync(join(root, '.hermes/plan-links.json'), 'utf8')).links || {}; } catch { return {}; } })();
const log = sh(`git log --format='@@%H|%h|%ad|%cI|%s' --name-only --date=short -- ${DS.join(' ')}`);
if (!log || !log.trim()) {
  if (!existsSync(out)) writeFileSync(out, JSON.stringify({ generated: new Date().toISOString(), continuation: CONTINUATION, plans, commits: [], wip: [] }, null, 1) + '\n');
  console.log('… ds-track: no DS log or git unavailable, manifest untouched');
  process.exit(0);
}
/* Two DS files are build-generated, never authored: this manifest rewrites
   itself at every run and arch-schema.json is regenerated by map-graph in
   build/predev. A commit whose only DS changes are those files is plumbing, not
   a build — excluding it keeps the generated manifest identical to the
   committed one, so routine runs never dirty the archive. */
const GENERATED = ['src/ds/changelog-manifest.json', 'src/ds/arch-schema.json'];
const commits = log.split(/^@@/m).filter(Boolean).map((block) => {
  const [head, ...files] = block.split('\n');
  const [full, sha, date, iso, ...rest] = head.split('|');
  const subject = rest.join('|');
  const m = subject.match(TAG);
  return {
    sha,
    full,
    date,
    time: (iso.match(/T(\d{2}:\d{2})/) || [])[1] || '',
    subject: subject.replace(TAG, '').trim(),
    plan: m ? m[1] : null,
    anchor: m ? (m[2] || null) : null,
    files: files.map((f) => f.trim()).filter(Boolean),
  };
}).filter((c) => c.files.some((f) => !GENERATED.includes(f))).map(({ files, ...c }) => c);
const st = sh(`git status --short -- ${DS.join(' ')}`) || '';
/* Build-generated files never count as wip — listing them shows up as
   "Uncommitted:" on every deployed changelog. */
const wip = st.trim() ? st.trim().split('\n').map((l) => l.trim()).filter(Boolean)
  .filter((l) => !GENERATED.some((g) => l.endsWith(g))) : [];
/* Vercel builds from a shallow clone (--depth=10), so git log there only sees
   the latest commits. Never let a truncated history overwrite the full one:
   merge fresh commits over the last committed manifest (dedupe by sha). */
let prevDoc = null;
let prev = [];
try { prevDoc = JSON.parse(readFileSync(out, 'utf8')); prev = prevDoc.commits || []; } catch { prev = []; }
const seen = new Set(commits.map((c) => c.sha));
prev.forEach((c) => { if (!seen.has(c.sha)) { commits.push(c); seen.add(c.sha); } });
commits.forEach((c) => { const r = retro[c.sha]; if (r) { c.plan = r.plan; c.anchor = r.anchor ?? null; } });
// Portfolio shas live in plan-links.json but never touch DS paths — without this they stay invisible to the calendar/heat graph and hit badges.
// Inject any retro-linked sha not already in the DS log so the changelog shows it as a tracked commit.
Object.keys(retro).forEach((short) => {
  if (commits.some((c) => c.sha === short)) return;
  const line = sh(`git show -s --format='%H|%h|%ad|%cI|%s' --date=short ${short}`);
  if (!line) return;
  const head = line.trim().split('\n')[0];
  if (!head) return;
  const [full, sha, date, iso, ...rest] = head.split('|');
  if (!full || !sha) return;
  const subject = rest.join('|');
  const r = retro[sha] || retro[short];
  if (!r) return;
  const time = (iso.match(/T(\d{2}:\d{2})/) || [])[1] || '';
  const m = subject.match(TAG);
  commits.push({ sha, full, date, time, subject: m ? subject.replace(TAG, '').trim() : subject.trim(), plan: r.plan, anchor: r.anchor ?? null });
});
commits.sort((a, b) => (b.date + (b.time || '')).localeCompare(a.date + (a.time || '')));
const shallow = (sh(`git rev-parse --is-shallow-repository`) || '').trim() === 'true';
if (shallow) console.log(`… ds-track: shallow clone detected, merged ${commits.length} commits (kept full history)`);
/* Keep the previous stamp when only the timestamp would change: a dev run or
   build must never leave the manifest dirty in git for no reason (a new DS
   commit still rewrites it, and that rewrite is what the ship SOP commits). */
const doc = { generated: new Date().toISOString(), continuation: CONTINUATION, plans, commits, wip };
const strip = (o) => JSON.stringify({ ...o, generated: null });
if (prevDoc && strip(prevDoc) === strip(doc)) doc.generated = prevDoc.generated;
writeFileSync(out, JSON.stringify(doc, null, 1) + '\n');
console.log(`✓ ds-track — ${plans.length} plans (${tagged}/${phased.length} tagged) · ${commits.length} DS commits (${commits.filter((c) => c.plan).length} linked) · ${wip.length} wip · cont ${CONTINUATION}`);
