/* ADAM/DS foundations · Color pane — ramp → semantic → usage + mixer + contrast. */
import { tokenTrace, note } from '../specimens.js';
const MIX = ['--color-ink', '--color-bg', '--color-accent', '--color-surface', '--color-surface-sunken', '--color-overlay'];
export const label = 'Color';
export function html() {
  return `<div class="ds-sec"><h2>Color</h2><p class="sub">Stone ramp + one vermilion step. UI consumes semantic names, never the ramp.</p><h3>Semantic — light / dark</h3>`
  + tokenTrace({ ramp: ['--stone-0', '--stone-25', '--stone-50', '--stone-100', '--stone-200', '--stone-300', '--stone-400', '--stone-500', '--stone-600', '--stone-700', '--stone-800', '--stone-900', '--stone-950'], rows: [['Background', '--color-bg', 'page + cards'], ['Surface', '--color-surface', 'cards + doc cells'], ['Ink', '--color-ink', 'headlines + primary buttons'], ['Muted', '--color-ink-muted', 'meta + kickers + labels'], ['Line · 10% ink', '--color-line', 'hairlines + card borders'], ['Accent', '--color-accent', 'callouts + badge + CTA rule'], ['On media', '--color-on-media', 'card info + tags on image'], ['Chip · 62% ink', '--color-chip', 'tags + filter pills'], ['Surface sunken', '--color-surface-sunken', 'wells + sunken rows'], ['Ink subtle', '--color-ink-subtle', 'faintest meta'], ['On accent', '--color-on-accent', 'text on accent'], ['On-media muted', '--color-on-media-muted', 'secondary on image'], ['Panel', '--color-panel', 'doc cells + hover'], ['Header frost', '--color-header', 'sticky header'], ['Overlay', '--color-overlay', 'viewer + modal'], ['Overlay muted', '--color-overlay-muted', 'secondary on overlay']] })
  + `<div class="vl" style="font-family:var(--font-mono);font-size:var(--text-label);color:var(--color-ink-muted)">Ramps ref-only — never consume directly · stone 0–950 · <span class="tok">--accent-500</span> is the only production vermilion</div>`
  + note('Do', 'Dark theme is a hand-tuned inversion (<span class="tok">prefers-color-scheme</span> + <span class="tok">[data-theme]</span> override), not a ramp swap. Toggle it top-right to proof every specimen.')
  + `</div><div class="ds-sec"><h2>Color explorer</h2><p class="sub">Mixer blends two opaque semantic tokens at <span class="tok">t</span>; contrast checker reads live <span class="tok">var()</span> ratios.</p><h3>Mixer — opaque tokens only</h3><div class="ds-spec block"><div id="mixSw" style="height:var(--space-60);border:var(--border-hairline);background:var(--color-ink)"></div><div class="fx-controls" id="mixCtrls"><label class="fx-row">A <select data-mix="a">${MIX.map((t) => `<option value="${t}">${t}</option>`).join('')}</select></label><label class="fx-row">B <select data-mix="b">${MIX.map((t) => `<option value="${t}"${t === '--color-accent' ? ' selected' : ''}>${t}</option>`).join('')}</select></label><label class="fx-row">t <input type="range" min="0" max="100" step="1" value="50" data-mix="t"><output data-mix-v="t">0.50</output></label><div class="fx-btns"><button class="tok" data-mix-copy="var">copy var()</button><button class="tok" data-mix-copy="hex">copy hex</button></div><div class="vl" id="mixVal" style="font-family:var(--font-mono);font-size:var(--text-micro)"></div></div></div><h3>Contrast — live computed</h3><table class="ds-table"><tr><th>Pair</th><th>Tokens</th><th>Ratio</th><th>Verdict</th></tr><tbody id="contrastBody"></tbody></table></div>`;
}
