/* ADAM/DS foundations · FX pane — graduation story + connected demos.
   Concept first: lab-local knobs → graduated --fx-* tokens → site consumption. */
import { tokenTrace, note } from '../specimens.js';
export const label = 'FX';
export function html() {
  return `<div class="ds-sec"><h2>FX · graduated</h2><p class="sub">Three layers: <b>lab-local</b> knobs (cell count, gutter, order — experiments, never tokens) → <b>graduated</b> <span class="tok">--fx-*</span> tokens (knobs proven on the site) → <b>site</b> consumption (gridReveal reads the same vars). Tweak a token, every demo below follows.</p>`
  + `<h3>Graduated tokens — what each runs</h3><p class="sub">Numbers, not colors — click any card to copy the live value.</p>`
  + tokenTrace({ plain: true, rows: [['Cell count', '--fx-cell', '30 · reveal grid count'], ['Stagger wait', '--fx-wait', '0.72 · pause between cell waves'], ['Photo from', '--fx-photo-from', '0.93 · photo settle start'], ['Morph', '--fx-morph', '0.04 · split ease'], ['Split end', '--fx-split-end', '0.92 · split end point'], ['Skeleton beat', '--fx-skeleton', '120ms · placeholder pulse'], ['Sheen band', '--fx-sheen', '0.14 · shimmer band width'], ['Grid pitch', '--fx-grid-pitch', '14px · reveal grid lines'], ['FX color', '--dur-fx-color', '240ms · cell tint sweep'], ['FX span', '--dur-fx-span', '0.6s · cell sweep span'], ['Hero rise', '--dur-hero-rise', '860ms · hero entrance']] })
  + `<h3>Grid pitch — live</h3><p class="sub">The reveal grid at <span class="tok" data-live="--fx-grid-pitch">--fx-grid-pitch</span>, painted by <span class="tok">--reveal-grid</span>. Full lab lives at <a href="#/functions/grid-reveal">GridReveal</a>.</p><div class="fd-grid-demo"></div>`
  + `<h3>Shimmer — live</h3><p class="sub">Skeleton sweep on <span class="tok">var(--dur-shimmer)</span> · band <span class="tok">var(--shimmer-band)</span> over <span class="tok">var(--shimmer-gradient)</span> · width <span class="tok">var(--fx-sheen)</span>. Toggle to freeze the band mid-flight.</p><div class="fx-shimmer" id="fxShimmer"><i></i></div><div class="fd-rowbtns"><button class="tok" data-shimmer-toggle>freeze / resume</button></div>`
  + `<h3>Rise — live</h3><p class="sub">Placeholder block settles on <span class="tok">var(--dur-glide)</span> with <span class="tok">var(--ease-signature)</span>. Replay the settle.</p><div class="fx-rise rest" id="fxRise"></div><div class="fd-rowbtns"><button class="tok" data-rise-replay>replay rise</button></div>`
  + `<h3>Press · hover — live</h3><p class="sub">Press the button (<span class="tok">var(--scale-press)</span> squash); hover the row (dims to <span class="tok">var(--opacity-hover)</span>). Definitions live in Motion · Depth.</p><div class="fd-rowbtns"><button class="fd-press">press me</button></div><div class="fd-hover">hover me — unselected rows dim to 0.55</div>`
  + `<h3>Elevation — live (hairline first)</h3><p class="sub">No UI card casts a shadow. Elevation is <span class="tok">--border-hairline</span> + surface, plus only two shadow jobs: keep type legible on media and lift the viewer. Toggle theme — <span class="tok">--shadow-viewer</span> flips from soft editorial (light) to heavier cut (dark). All shadow values are token-adherent: <span class="tok">travel = --space-*</span>, <span class="tok">color = --stone-950</span>, <span class="tok">opacity = --opacity-shadow-*</span> → <span class="tok">--color-shadow-*</span> via <span class="tok">color-mix</span>. Click any card to copy its live value.</p>`
  + `<div class="fd-elev-row">`
  + `<div class="fd-elev" data-copy-token=\"--border-hairline\" title=\"Click to copy live --border-hairline\" style=\"cursor:pointer\"><b>0 · flat</b><span class="tok">--border-hairline</span><small>every card / pill / thumb<br>surface on paper, 1px line</small><code data-live=\"--border-hairline\">--border-hairline</code></div>`
  + `<div class="fd-elev" data-copy-token=\"--color-surface-sunken\" title=\"Click to copy live --color-surface-sunken\" style=\"cursor:pointer;background:var(--color-surface-sunken)\"><b>–1 · sunken</b><span class="tok">--color-surface-sunken</span><small>inset ground — no shadow<br>disabled / well on paper</small><code data-live=\"--color-surface-sunken\">--color-surface-sunken</code></div>`
  + `<div class="fd-elev fd-elev--viewer" data-copy-token=\"--shadow-viewer\" title=\"Click to copy live --shadow-viewer\" style=\"cursor:pointer\"><b>1 · lifted</b><span class="tok">--shadow-viewer</span><small>viewer frame only<br><span class="tok">--space-12</span> / <span class="tok">--space-32</span> + <span class="tok">--space-2</span> / <span class="tok">--space-10</span> · theme 12→14 / 32→36</small><code data-live=\"--shadow-viewer\">--shadow-viewer</code></div>`
  + `<div class="fd-elev fd-elev--media" data-copy-token=\"--shadow-on-media\" title=\"Click to copy live --shadow-on-media\" style=\"cursor:pointer\"><b style="text-shadow:var(--shadow-on-media)">O · on-media</b><span class="tok">--shadow-on-media</span><small>text keeps legible on chip / image<br><span class="tok">--space-1</span> / <span class="tok">--space-10</span> / <span class="tok">--space-12</span></small><code data-live=\"--shadow-on-media\">--shadow-on-media</code></div>`
  + `</div>`
  + `<p class="sub" style="margin-top:calc(var(--space-6) * -1);font-family:var(--font-mono);font-size:var(--text-micro);color:var(--color-ink-muted)">Tip: the media card shows <span class="tok">text-shadow</span> (not box-shadow) — dark chip behind the title does the real lifting, shadow is the 1px crispener. Travel always <span class="tok">var(--space-*)</span>; color never raw <span class="tok">rgba()</span>.</p>`
  + tokenTrace({ plain: true, rows: [['Hairline', '--border-hairline', '0 flat — every card / thumb / pill'], ['Viewer', '--shadow-viewer', '0 var(--space-12) var(--space-32) + 0 var(--space-2) var(--space-10) · dark: 14/36 + 3/12'], ['On-media sm', '--shadow-on-media-sm', '0 var(--space-1) var(--space-10) · --color-shadow-media-sm'], ['On-media', '--shadow-on-media', '0 var(--space-1) var(--space-12) · --color-shadow-media']] })
  + `<p class="sub" style="font-family:var(--font-mono);font-size:var(--text-micro);color:var(--color-ink-muted)">Shadow recipe: travel var(--space-*) + color via color-mix — the four colors live in Color → Elevation with live swatches; opacity knobs below.</p>`
  + tokenTrace({ plain: true, rows: [['Opacity media', '--opacity-shadow-media', '45% · on-media lg'], ['Opacity media sm', '--opacity-shadow-media-sm', '40% · on-media sm'], ['Opacity viewer', '--opacity-shadow-viewer', '24% · lifted main (light+dark)'], ['Opacity viewer soft', '--opacity-shadow-viewer-soft', '12% · lifted soft (light+dark)']] })
  + `<h3>Viewer spring — live tokens</h3><p class="sub">Intent + spring the viewer route reads: threshold is intent travel, idle is dismiss wait, debounce settles the pointer, k / fr are spring stiffness / friction. Full lab at <a href="#/functions/viewer">Viewer</a>.</p>`
  + tokenTrace({ plain: true, rows: [['Threshold', '--fx-viewer-threshold', '12px · intent travel'], ['Idle', '--fx-viewer-idle', '850ms · dismiss wait'], ['Debounce', '--fx-viewer-debounce', '70ms · pointer settle'], ['Stiffness k', '--fx-viewer-k', '0.1 · spring stiffness'], ['Friction fr', '--fx-viewer-fr', '0.54 · spring friction']] })
  + tokenTrace({ plain: true, rows: [['Viewer border', '--viewer-border', 'frosted frame the viewer opens in'], ['Viewer shadow', '--shadow-viewer', 'lift off the page behind the frame'], ['Viewer in', '--dur-viewer-in', '300ms · open travel'], ['Viewer line', '--dur-viewer-line', '780ms · tether draw']] })
  + note('Do', 'Graduate knobs through tokens — lab-local count / gutter / order stay out of the contract.')
  + `</div>`;
}
