/* ADAM/DS foundations · Type pane — live var() scale + tester. */
import { tokenTrace, typeRow, note, code } from '../specimens.js';
export const label = 'Type';
export function html() {
  return `<div class="ds-sec"><h2>Typography</h2><p class="sub">Inter Tight for voice · Chivo Mono for metadata. Title parity: contact hero and case h1 share <span class="tok">--text-title</span>. Every sample is live <span class="tok">var()</span> type.</p><table class="ds-table"><tr><th>Sample</th><th>Token</th><th>Spec</th></tr>`
  + typeRow('<b style="font-size:var(--text-display);font-weight:800;letter-spacing:var(--tracking-display);line-height:var(--leading-display)">Display</b>', '--text-display', 'clamp(28,5vw,54) · 800 · −0.04 · lh 0.9')
  + typeRow('<b style="font-size:var(--text-title);font-weight:700;letter-spacing:var(--tracking-title);line-height:var(--leading-title)">Title · h1</b>', '--text-title', 'clamp(26,4.5vw,46) · 700 · −0.03 · lh 1.1')
  + typeRow('<b style="font-size:var(--text-logo);font-weight:800">Logo</b>', '--text-logo', '22px · 800 · brand mark')
  + typeRow('<b style="font-size:var(--text-h2);font-weight:700;letter-spacing:var(--tracking-heading)">Section h2</b>', '--text-h2', '20px · 700 · −0.02')
  + typeRow('<b style="font-size:var(--text-card-title);font-weight:600">Card title</b>', '--text-card-title', '18px · 600')
  + typeRow('<b style="font-size:var(--text-h3);font-weight:600">Section h3</b>', '--text-h3', '16px · 600')
  + typeRow('<span style="font-size:var(--text-body);line-height:var(--leading-body)">Body 14px/1.5, prose 1.6.</span>', '--text-body', 'Inter Tight · max 60–68ch')
  + typeRow('<span style="font-size:var(--text-small);font-weight:600">Small — card titles 13.5px.</span>', '--text-small', '13.5px · 600 · −0.01 · lh 1.25')
  + typeRow('<span style="font-family:var(--font-mono);font-size:var(--text-meta)">MONO META · 12PX</span>', '--text-meta', 'Chivo Mono · work meta, kickers')
  + typeRow('<span style="font-family:var(--font-mono);font-size:var(--text-label);letter-spacing:var(--tracking-mono)">LABEL · 11PX · TRACK .1</span>', '--text-label', 'Chivo Mono · tags, spec dt')
  + typeRow('<span style="font-family:var(--font-mono);font-size:var(--text-micro);letter-spacing:var(--tracking-mono)">MICRO · 10.5PX</span>', '--text-micro', 'Chivo Mono · captions, crumbs')
  + `</table>`
  + tokenTrace({ rows: [['Leading display', '--leading-display', '0.9 · hero'], ['Leading title', '--leading-title', '1.1 · h1'], ['Leading snug', '--leading-snug', '1.25 · cards'], ['Leading body', '--leading-body', '1.5 · ui'], ['Leading prose', '--leading-prose', '1.6 · long read'], ['Leading mono', '--leading-mono', '1.3 · code'], ['Tracking display', '--tracking-display', '-0.04em · tight'], ['Tracking title', '--tracking-title', '-0.03em · h1'], ['Tracking heading', '--tracking-heading', '-0.02em · sections'], ['Tracking body', '--tracking-body', '-0.01em · text'], ['Tracking label', '--tracking-label', '0.12em · labels'], ['Tracking mono', '--tracking-mono', '0.1em · mono']] })
  + code('weight — regular 400 · medium 500 · semibold 600 · bold 700 · extrabold 800')
  + note('Do', 'Pair sizes with their leading + tracking tokens — never set a bare <span class="tok">font-size</span> without its line-height.')
  + `<h3>Type tester — live</h3><div class="ds-spec block"><div id="typeSample" contenteditable="true" style="font-family:var(--font-sans);font-size:var(--text-body);line-height:var(--leading-body);letter-spacing:var(--tracking-body);border:var(--border-hairline);padding:var(--space-12);background:var(--color-surface);min-height:var(--space-60)">The quick brown fox — edit me. Inter Tight renders voice.</div><div class="fx-controls" id="typeCtrls"><label class="fx-row">size <select data-type="size"><option value="var(--text-small)">small 13.5</option><option value="var(--text-body)" selected>body 14</option><option value="var(--text-h3)">h3 16</option><option value="var(--text-title)">title</option><option value="var(--text-display)">display</option></select></label><label class="fx-row">leading <select data-type="leading"><option value="var(--leading-body)">body 1.5</option><option value="var(--leading-snug)">snug 1.25</option><option value="var(--leading-prose)">prose 1.6</option><option value="var(--leading-display)">display 0.9</option></select></label><label class="fx-row">tracking <select data-type="tracking"><option value="var(--tracking-body)" selected>body -.01</option><option value="var(--tracking-heading)">heading -.02</option><option value="var(--tracking-title)">title -.03</option><option value="var(--tracking-display)">display -.04</option><option value="var(--tracking-label)">label .12</option><option value="var(--tracking-mono)">mono .1</option></select></label></div></div></div>`;
}
