/* ADAM/DS foundations · FX pane — graduation story + connected demos.
   Concept first: lab-local knobs → graduated --fx-* tokens → site consumption. */
import { tokenTrace, note } from '../specimens.js';
export const label = 'FX';
export function html() {
  return `<div class="ds-sec"><h2>FX · graduated</h2><p class="sub">Three layers: <b>lab-local</b> knobs (cell count, gutter, order — experiments, never tokens) → <b>graduated</b> <span class="tok">--fx-*</span> tokens (knobs proven on the site) → <b>site</b> consumption (gridReveal reads the same vars). Tweak a token, every demo below follows.</p>`
  + `<h3>Graduated tokens — what each runs</h3><p class="sub">Numbers, not colors — click any card to copy the live value.</p>`
  + tokenTrace({ plain: true, rows: [['Cell count', '--fx-cell', '30 · reveal grid count'], ['Stagger wait', '--fx-wait', '0.72 · pause between cell waves'], ['Photo from', '--fx-photo-from', '0.93 · photo settle start'], ['Morph', '--fx-morph', '0.04 · split ease'], ['Split end', '--fx-split-end', '0.92 · split end point'], ['Skeleton beat', '--fx-skeleton', '120ms · placeholder pulse'], ['Sheen band', '--fx-sheen', '0.14 · shimmer band width'], ['Grid pitch', '--fx-grid-pitch', '14px · reveal grid lines'], ['FX color', '--dur-fx-color', '240ms · cell tint sweep'], ['FX span', '--dur-fx-span', '0.6s · cell sweep span'], ['Hero rise', '--dur-hero-rise', '860ms · hero entrance']] })
  + `<h3>Grid pitch — live</h3><p class="sub">The reveal grid at <span class="tok" data-live="--fx-grid-pitch">--fx-grid-pitch</span>, painted by <span class="tok">--reveal-grid</span>. Full lab lives at <a href="#/functions/grid-reveal">GridReveal</a>.</p><div class="fd-grid-demo"></div>`
  + `<h3>Shimmer — live</h3><p class="sub">Skeleton sweep on <span class="tok">var(--dur-shimmer)</span> · band <span class="tok">var(--shimmer-band)</span> over <span class="tok">var(--shimmer-gradient)</span> · width <span class="tok">var(--fx-sheen)</span>. Toggle to freeze the band mid-flight.</p><div class="fx-shimmer" id="fxShimmer"><i></i></div><div class="fd-rowbtns"><button class="tok" data-shimmer-toggle>freeze / resume</button></div>`
  + `<h3>Rise — live</h3><p class="sub">Placeholder block settles on <span class="tok">var(--dur-glide)</span> with <span class="tok">var(--ease-signature)</span>. Replay the settle.</p><div class="fx-rise rest" id="fxRise"></div><div class="fd-rowbtns"><button class="tok" data-rise-replay>replay rise</button></div>`
  + `<h3>Press · hover — live</h3><p class="sub">Press the button (<span class="tok">var(--scale-press)</span> squash); hover the row (dims to <span class="tok">var(--opacity-hover)</span>). Definitions live in Motion · Depth.</p><div class="fd-rowbtns"><button class="fd-press">press me</button></div><div class="fd-hover">hover me — unselected rows dim to 0.55</div>`
  + `<h3>Viewer spring — live tokens</h3><p class="sub">Intent + spring the viewer route reads: threshold is intent travel, idle is dismiss wait, debounce settles the pointer, k / fr are spring stiffness / friction. Full lab at <a href="#/functions/viewer">Viewer</a>.</p>`
  + tokenTrace({ plain: true, rows: [['Threshold', '--fx-viewer-threshold', '12px · intent travel'], ['Idle', '--fx-viewer-idle', '850ms · dismiss wait'], ['Debounce', '--fx-viewer-debounce', '70ms · pointer settle'], ['Stiffness k', '--fx-viewer-k', '0.1 · spring stiffness'], ['Friction fr', '--fx-viewer-fr', '0.54 · spring friction']] })
  + tokenTrace({ plain: true, rows: [['Viewer border', '--viewer-border', 'frosted frame the viewer opens in'], ['Viewer shadow', '--shadow-viewer', 'lift off the page behind the frame'], ['Viewer in', '--dur-viewer-in', '300ms · open travel'], ['Viewer line', '--dur-viewer-line', '780ms · tether draw']] })
  + note('Do', 'Graduate knobs through tokens — lab-local count / gutter / order stay out of the contract.')
  + `</div>`;
}
