/* ADAM/DS foundations · Color pane — ① primitives → ② semantic → ③ playground → ④ proof (Update 4 Phase 1 + Task 7). */
import { tokenTrace, note } from '../specimens.js';
const MIX = ['--color-ink', '--color-bg', '--color-accent', '--color-surface', '--color-surface-sunken', '--color-overlay', '--color-success', '--color-error', '--color-warning', '--color-info'];
const STONE = ['--stone-0', '--stone-25', '--stone-50', '--stone-100', '--stone-200', '--stone-300', '--stone-400', '--stone-500', '--stone-600', '--stone-700', '--stone-800', '--stone-900', '--stone-950'];
const ACCENT = ['--accent-100', '--accent-300', '--accent-500', '--accent-600', '--accent-700', '--accent-900'];
const ACCENT2 = ['--accent2-100', '--accent2-300', '--accent2-500', '--accent2-600', '--accent2-700', '--accent2-900'];
const ACCENT3 = ['--accent3-100', '--accent3-300', '--accent3-500', '--accent3-600', '--accent3-700', '--accent3-900'];
const short = (t) => t.slice(2);
const rampRows = (tokens, use) => tokens.map((t) => [short(t), t, use]);
const badge = (nm, bg, fg, use) => `<div class="ds-cell"><div style="background:var(${bg});color:var(${fg});padding:var(--space-8) var(--space-14);font-size:var(--text-small);border:var(--border-hairline)">${nm} — live pair, both themes</div><div class="nm">${nm}</div><div class="vl"><span class="tok">${bg}</span> on <span class="tok">${fg}</span></div><div class="vl">${use}</div></div>`;
export const label = 'Color';
export function html() {
  return `<style id="cand-cool">:root{--cand-a-0:#ffffff;--cand-a-25:#f8f9fb;--cand-a-50:#f2f4f7;--cand-a-100:#eceef2;--cand-a-200:#e2e6ea;--cand-a-300:#d0d6dc;--cand-a-400:#9aa5b1;--cand-a-500:#737e8a;--cand-a-600:#56606d;--cand-a-700:#353d46;--cand-a-800:#1e2329;--cand-a-900:#15191f;--cand-a-950:#12151a;--cand-b-0:#ffffff;--cand-b-25:#f6f8fb;--cand-b-50:#eef2f7;--cand-b-100:#e8ecf1;--cand-b-200:#d9dfe8;--cand-b-300:#c2ccda;--cand-b-400:#8f9bb0;--cand-b-500:#67748b;--cand-b-600:#4a5568;--cand-b-700:#2e3442;--cand-b-800:#1c212d;--cand-b-900:#131722;--cand-b-950:#0f1320;--cand-c-0:#ffffff;--cand-c-25:#f4f7fb;--cand-c-50:#e9eef6;--cand-c-100:#e1e7f0;--cand-c-200:#cfd8e6;--cand-c-300:#b6c2d6;--cand-c-400:#8596b2;--cand-c-500:#5e6b85;--cand-c-600:#3f4a63;--cand-c-700:#262d3d;--cand-c-800:#171d2a;--cand-c-900:#0f1320;--cand-c-950:#0c101c}</style><div class="ds-sec"><h2>Color</h2><p class="sub">Stone ramp + three accents (vermilion · amber · teal). UI consumes semantic names, never the ramp. Feedback roles ride the ramps: error on vermilion, warning on amber, success + info on teal.</p>`
  + `<h3>① Primitives — ref-only</h3><p class="sub">Horizontal strip first, every step labeled in-swatch below, both themes. Reference only — consume the semantic name, not the step.</p><h3>Stone · neutral 0–950</h3>`
  + tokenTrace({ ramp: STONE, rows: rampRows(STONE, 'neutral primitive · never consume directly') })
  + `<div class="ds-note" style="margin-top:var(--space-16)"><b>Candidates — cool ramps (Phase 1 · temp)</b> Blue-gray specimens eyeballed, not consumed. Pick one → stone retune. <b>Pick: B — Alloy</b> (crisp synthetic, slate-blue 215°, balanced AA).</div>`
  + `<h3 style="margin-top:var(--space-12)">Candidate A · Frost — subtle ice (220° · low chroma)</h3><div class="ds-ramp">${['--cand-a-0','--cand-a-25','--cand-a-50','--cand-a-100','--cand-a-200','--cand-a-300','--cand-a-400','--cand-a-500','--cand-a-600','--cand-a-700','--cand-a-800','--cand-a-900','--cand-a-950'].map((v)=>`<i style="background:var(${v})" title="${v}"></i>`).join('')}</div><div class="ds-grid c4">${[['0','#ffffff','--cand-a-0'],['25','#f8f9fb','--cand-a-25'],['50','#f2f4f7','--cand-a-50'],['100','#eceef2','--cand-a-100'],['200','#e2e6ea','--cand-a-200'],['300','#d0d6dc','--cand-a-300'],['400','#9aa5b1','--cand-a-400'],['500','#737e8a','--cand-a-500'],['600','#56606d','--cand-a-600'],['700','#353d46','--cand-a-700'],['800','#1e2329','--cand-a-800'],['900','#15191f','--cand-a-900'],['950','#12151a','--cand-a-950']].map(([n,hex,v])=>`<div class="ds-cell"><div class="ds-sw" style="background:var(${v})"></div><div class="nm">${n}</div><div class="vl"><span class="tok">${v}</span></div><div class="vl">${hex}</div></div>`).join('')}</div>`
  + `<h3>Candidate B · Alloy — crisp synthetic ★ pick (215° · slate-blue, AA-balanced)</h3><div class="ds-ramp">${['--cand-b-0','--cand-b-25','--cand-b-50','--cand-b-100','--cand-b-200','--cand-b-300','--cand-b-400','--cand-b-500','--cand-b-600','--cand-b-700','--cand-b-800','--cand-b-900','--cand-b-950'].map((v)=>`<i style="background:var(${v})" title="${v}"></i>`).join('')}</div><div class="ds-grid c4">${[['0','#ffffff','--cand-b-0'],['25','#f6f8fb','--cand-b-25'],['50','#eef2f7','--cand-b-50'],['100','#e8ecf1','--cand-b-100'],['200','#d9dfe8','--cand-b-200'],['300','#c2ccda','--cand-b-300'],['400','#8f9bb0','--cand-b-400'],['500','#67748b','--cand-b-500'],['600','#4a5568','--cand-b-600'],['700','#2e3442','--cand-b-700'],['800','#1c212d','--cand-b-800'],['900','#131722','--cand-b-900'],['950','#0f1320','--cand-b-950']].map(([n,hex,v])=>`<div class="ds-cell"><div class="ds-sw" style="background:var(${v})"></div><div class="nm">${n}</div><div class="vl"><span class="tok">${v}</span></div><div class="vl">${hex}</div></div>`).join('')}</div>`
  + `<h3>Candidate C · Synth Slate — deep tech (220° · higher chroma)</h3><div class="ds-ramp">${['--cand-c-0','--cand-c-25','--cand-c-50','--cand-c-100','--cand-c-200','--cand-c-300','--cand-c-400','--cand-c-500','--cand-c-600','--cand-c-700','--cand-c-800','--cand-c-900','--cand-c-950'].map((v)=>`<i style="background:var(${v})" title="${v}"></i>`).join('')}</div><div class="ds-grid c4">${[['0','#ffffff','--cand-c-0'],['25','#f4f7fb','--cand-c-25'],['50','#e9eef6','--cand-c-50'],['100','#e1e7f0','--cand-c-100'],['200','#cfd8e6','--cand-c-200'],['300','#b6c2d6','--cand-c-300'],['400','#8596b2','--cand-c-400'],['500','#5e6b85','--cand-c-500'],['600','#3f4a63','--cand-c-600'],['700','#262d3d','--cand-c-700'],['800','#171d2a','--cand-c-800'],['900','#0f1320','--cand-c-900'],['950','#0c101c','--cand-c-950']].map(([n,hex,v])=>`<div class="ds-cell"><div class="ds-sw" style="background:var(${v})"></div><div class="nm">${n}</div><div class="vl"><span class="tok">${v}</span></div><div class="vl">${hex}</div></div>`).join('')}</div>`
  + `<h3>Accent · vermilion ramp (red / orange)</h3><p class="sub"><span class="tok">--accent-500</span> is the only production vermilion; the other steps exist for tints, shades, and error states.</p>`
  + tokenTrace({ ramp: ACCENT, rows: rampRows(ACCENT, 'accent step · prefer --color-accent') })
  + `<h3>Accent2 · amber ramp (yellow / neon)</h3><p class="sub">Warning family. Text + fill dual-use steps: <span class="tok">--accent2-700</span> on light, <span class="tok">--accent2-300</span> on dark. <span class="tok">--accent2-500</span> is decorative only (borders, large graphics).</p>`
  + tokenTrace({ ramp: ACCENT2, rows: rampRows(ACCENT2, 'amber step · prefer --color-warning') })
  + `<h3>Accent3 · teal ramp (blue / green)</h3><p class="sub">Success + info share one hue, split by depth + icon: success deepest (<span class="tok">-700</span> / <span class="tok">-300</span>), info mid (<span class="tok">-600</span> / <span class="tok">-100</span>).</p>`
  + tokenTrace({ ramp: ACCENT3, rows: rampRows(ACCENT3, 'teal step · prefer --color-success / --color-info') })
  + note('Do', 'Three accents, settled (Task 7): <span class="tok">--accent-*</span> vermilion · <span class="tok">--accent2-*</span> amber · <span class="tok">--accent3-*</span> teal. New hues stop here — anything else arrives as a component token, never a fourth ramp.')
  + `<h3>② Semantic — light / dark</h3><p class="sub">Every <span class="tok">--color-*</span> under exactly one purpose group. Toggle the theme top-right to proof both.</p><h3>Canvas</h3>`
  + tokenTrace({ rows: [['Background', '--color-bg', 'page + cards'], ['Surface', '--color-surface', 'cards + doc cells'], ['Surface sunken', '--color-surface-sunken', 'wells + sunken rows'], ['Overlay', '--color-overlay', 'viewer + modal'], ['Panel', '--color-panel', 'doc cells + hover']] })
  + `<h3>Ink</h3>`
  + tokenTrace({ rows: [['Ink', '--color-ink', 'headlines + primary buttons'], ['Muted', '--color-ink-muted', 'meta + kickers + labels'], ['Ink subtle', '--color-ink-subtle', 'faintest meta'], ['Overlay muted', '--color-overlay-muted', 'secondary on overlay']] })
  + `<h3>Division</h3>`
  + tokenTrace({ rows: [['Line · 10% ink', '--color-line', 'hairlines + card borders'], ['Header frost', '--color-header', 'sticky header']] })
  + `<h3>Action</h3>`
  + tokenTrace({ rows: [['Accent', '--color-accent', 'callouts + badge + CTA rule'], ['On accent', '--color-on-accent', 'text on accent'], ['Chip · 62% ink', '--color-chip', 'tags + filter pills'], ['Input bg', '--color-input-bg', 'field fill'], ['Input line', '--color-input-line', 'field border'], ['Input focus', '--color-input-focus', 'field focus edge']] })
  + `<h3>Media</h3>`
  + tokenTrace({ rows: [['On media', '--color-on-media', 'card info + tags on image'], ['On-media muted', '--color-on-media-muted', 'secondary on image'], ['Viewer bg', '--color-viewer-bg', 'viewer panel'], ['Viewer line', '--color-viewer-line', 'viewer frosted border'], ['Viewer shade', '--color-viewer-shade', 'viewer dim'], ['Viewer tether', '--color-viewer-tether', 'viewer connector']] })
  + `<h3>State</h3>`
  + tokenTrace({ rows: [['Disabled bg', '--color-disabled-bg', 'disabled fill'], ['Disabled ink', '--color-disabled-ink', 'disabled text'], ['Disabled line', '--color-disabled-line', 'disabled border'], ['Focus', '--color-focus', 'keyboard ring, all themes']] })
  + `<h3>Feedback (Task 7)</h3><p class="sub">One token doubles as text-on-paper and fill-with-on-color — each pair AA in both themes (proof table below, live probe).</p>`
  + tokenTrace({ rows: [['Success', '--color-success', 'accent3-700 light / 300 dark · form ok + sent hints'], ['On success', '--color-on-success', 'text on success fill'], ['Error', '--color-error', 'accent-700 light / 300 dark · replaces bare --color-accent for errors'], ['On error', '--color-on-error', 'text on error fill'], ['Warning', '--color-warning', 'accent2-700 light / 300 dark · cautions'], ['On warning', '--color-on-warning', 'text on warning fill'], ['Info', '--color-info', 'accent3-600 light / 100 dark · neutral notices'], ['On info', '--color-on-info', 'text on info fill']] })
  + `<div class="ds-grid c2">${badge('Success', '--color-success', '--color-on-success', 'sent · ok')}${badge('Error', '--color-error', '--color-on-error', 'field error · failed')}${badge('Warning', '--color-warning', '--color-on-warning', 'caution · unsaved')}${badge('Info', '--color-info', '--color-on-info', 'notice · hint')}</div>`
  + `<div class="ds-grid c2"><div class="ds-cell"><div style="background:var(--color-disabled-bg);color:var(--color-disabled-ink);border:var(--space-1) solid var(--color-disabled-line);padding:var(--space-8) var(--space-14);font-size:var(--text-small)">Disabled specimen — not interactive</div><div class="nm">Disabled</div><div class="vl">bg + ink + line · both themes</div></div><div class="ds-cell"><div style="outline:var(--border-focus);outline-offset:var(--focus-offset);padding:var(--space-8) var(--space-14);font-size:var(--text-small)">Focus ring — Tab to any control to see it live</div><div class="nm">Focus ring</div><div class="vl"><span class="tok">--border-focus</span> + <span class="tok">--focus-offset</span> · full spec lives in Shape</div></div></div>`
  + note('Do', 'Dark theme is a hand-tuned inversion (<span class="tok">prefers-color-scheme</span> + <span class="tok">[data-theme]</span> override), not a ramp swap. Toggle it top-right to proof every specimen.')
  + `</div><div class="ds-sec"><h2>Color explorer</h2><p class="sub">Playground, demoted below the system. Mixer blends two opaque semantic tokens at <span class="tok">t</span>; proof reads live <span class="tok">var()</span> ratios.</p><h3>③ Playground — mixer, opaque tokens only</h3><div class="ds-spec block"><div id="mixSw" style="height:var(--space-60);border:var(--border-hairline);background:var(--color-ink)"></div><div class="fx-controls" id="mixCtrls"><label class="fx-row">A <select data-mix="a">${MIX.map((t) => `<option value="${t}">${t}</option>`).join('')}</select></label><label class="fx-row">B <select data-mix="b">${MIX.map((t) => `<option value="${t}"${t === '--color-accent' ? ' selected' : ''}>${t}</option>`).join('')}</select></label><label class="fx-row">t <input type="range" min="0" max="100" step="1" value="50" data-mix="t"><output data-mix-v="t">0.50</output></label><div class="fx-btns"><button class="tok" data-mix-copy="var">copy var()</button><button class="tok" data-mix-copy="hex">copy hex</button></div><div class="vl" id="mixVal" style="font-family:var(--font-mono);font-size:var(--text-micro)"></div></div></div>`
  + `<h3>④ Proof — full contrast matrix, both themes</h3><p class="sub">Every text ink × canvas, probed live in light + dark via <span class="tok">probeTheme</span> — this table already shows both, no toggle needed.</p><table class="ds-table"><tr><th>Pair</th><th>Tokens</th><th>Ratio</th><th>Verdict</th></tr><tbody id="contrastBody"></tbody></table>`
  + `<h3>Feedback proof — roles × paper, both themes</h3><p class="sub">Each role as text on paper/surface plus its on-color on the role fill — live probe, AA or better.</p><table class="ds-table"><tr><th>Pair</th><th>Tokens</th><th>Ratio</th><th>Verdict</th></tr><tbody id="feedbackBody"></tbody></table></div>`;
}
