graph TD
ds_atlas_actions --> ds_atlas_camera
ds_atlas_actions --> ds_atlas_insight
ds_atlas_actions --> ds_atlas_schema
ds_atlas_actions --> ds_atlas_search
ds_atlas_camera --> ds_atlas_layout
ds_atlas_canvas --> ds_atlas_layout
ds_atlas_canvas --> ds_atlas_wire
ds_atlas_dock --> ds_atlas_schema
ds_atlas_dock --> ds_atlas_search
ds_atlas_insight --> ds_atlas_schema
ds_atlas_panel --> ds_atlas_schema
ds_atlas_search --> ds_atlas_schema
ds_atlas_shell --> ds_atlas_dock
ds_atlas_tooltip --> ds_atlas_panel
ds_atlas_view --> ds_atlas_camera
ds_atlas_view --> ds_atlas_canvas
ds_atlas_view --> ds_atlas_insight
ds_changelog_events --> views_element_sound
ds_changelog_events --> views_glitch_sound_timing
ds_changelog_graph --> ds_changelog_links
ds_changelog_graph --> ds_changelog_parse
ds_changelog_paint --> ds_changelog_paint_chips
ds_changelog_paint --> ds_changelog_paint_detail
ds_changelog_paint --> ds_changelog_paint_plan
ds_changelog_paint_chips --> ds_changelog_graph
ds_changelog_paint_chips --> ds_changelog_parse
ds_changelog_paint_detail --> ds_changelog_esc
ds_changelog_paint_detail --> ds_changelog_links
ds_changelog_paint_detail --> ds_changelog_parse
ds_changelog_paint_detail --> ds_changelog_titles
ds_changelog_paint_plan --> ds_changelog_esc
ds_changelog_paint_plan --> ds_changelog_links
ds_changelog_paint_plan --> ds_changelog_parse
ds_changelog_paint_plan --> ds_changelog_titles
ds_component --> ds_component_knobs
ds_component --> ds_specimens
ds_component --> ds_tabs
ds_ds --> ds_routes
ds_ds --> ds_sidebar
ds_ds --> ds_specimens
ds_ds --> ds_tabs
ds_ds --> ds_theme
ds_foundations_color_sections --> ds_foundations_color_data
ds_foundations_fx_elev --> ds_specimens
ds_foundations_fx_spring --> ds_specimens
ds_foundations_fx_tokens --> ds_specimens
ds_foundations_mix --> ds_specimens
ds_foundations_motion_sections --> ds_foundations_motion_data
ds_foundations_pane_color --> ds_foundations_color_data
ds_foundations_pane_color --> ds_foundations_color_sections
ds_foundations_pane_color --> ds_specimens
ds_foundations_pane_contract --> ds_specimens
ds_foundations_pane_fx --> ds_foundations_fx_demos
ds_foundations_pane_fx --> ds_foundations_fx_elev
ds_foundations_pane_fx --> ds_foundations_fx_spring
ds_foundations_pane_fx --> ds_foundations_fx_tokens
ds_foundations_pane_motion --> ds_foundations_motion_sections
ds_foundations_pane_motion --> ds_specimens
ds_foundations_pane_shape --> ds_foundations_shape_borders
ds_foundations_pane_shape --> ds_foundations_shape_doctrine
ds_foundations_pane_shape --> ds_foundations_shape_focus
ds_foundations_pane_shape --> ds_foundations_shape_radius
ds_foundations_pane_shape --> ds_specimens
ds_foundations_pane_space --> ds_foundations_space_audit
ds_foundations_pane_space --> ds_foundations_space_layout
ds_foundations_pane_space --> ds_foundations_space_scale
ds_foundations_pane_space --> ds_foundations_space_tables
ds_foundations_pane_space --> ds_specimens
ds_foundations_pane_type --> ds_foundations_type_playground
ds_foundations_pane_type --> ds_foundations_type_scale
ds_foundations_pane_type --> ds_foundations_type_voice
ds_foundations_shape_borders --> ds_specimens
ds_foundations_shape_focus --> ds_specimens
ds_foundations_shape_radius --> ds_specimens
ds_foundations_space_tables --> ds_specimens
ds_foundations_type_playground --> ds_specimens
ds_foundations_type_scale --> ds_foundations_type_demos
ds_foundations_type_scale --> ds_specimens
ds_foundations_type_voice --> ds_specimens
ds_functions_glimmer_orb --> ds_specimens
ds_functions_glimmer_orb --> ds_views_glimmer_orb
ds_functions_glimmer_orb --> views_glimmer_orb
ds_functions_glitch --> ds_functions_glitch_lab_controls
ds_functions_glitch --> ds_functions_glitch_sound_bind
ds_functions_glitch --> ds_functions_glitch_sound_panel
ds_functions_glitch --> ds_functions_glitch_sound_play
ds_functions_glitch --> ds_functions_glitch_source_panel
ds_functions_glitch --> ds_specimens
ds_functions_glitch --> ds_views_glitch
ds_functions_glitch --> views_glitch_sound
ds_functions_glitch_lab_controls --> views_glitch
ds_functions_glitch_meta --> views_glitch_sound
ds_functions_glitch_meta --> views_sound_files
ds_functions_glitch_sound_bind --> ds_functions_glitch_meta
ds_functions_glitch_sound_bind --> views_audio_ctx
ds_functions_glitch_sound_bind --> views_element_sound
ds_functions_glitch_sound_bind --> views_sound_files
ds_functions_glitch_sound_bind --> views_sound_source
ds_functions_glitch_sound_panel --> ds_functions_glitch_meta
ds_functions_glitch_sound_play --> views_audio_ctx
ds_functions_glitch_sound_play --> views_element_sound
ds_functions_glitch_sound_play --> views_glitch
ds_functions_glitch_sound_play --> views_sound_source
ds_functions_glitch_source_markup --> ds_functions_glitch_meta
ds_functions_glitch_source_markup --> views_sound_source
ds_functions_glitch_source_panel --> ds_functions_glitch_source_markup
ds_functions_glitch_source_panel --> views_element_sound
ds_functions_glitch_source_panel --> views_sound_source
ds_functions_grid_reveal --> ds_functions_grid_reveal_docs
ds_functions_grid_reveal --> ds_functions_grid_reveal_lab
ds_functions_grid_reveal --> ds_fx_lab
ds_functions_grid_reveal_docs --> ds_specimens
ds_functions_grid_reveal_lab --> ds_specimens
ds_functions_grid_reveal_lab --> ds_views_masonry_cells
ds_functions_grid_reveal_lab --> ds_views_masonry_gridReveal
ds_functions_rise --> ds_fx_lab
ds_functions_rise --> ds_specimens
ds_functions_scramble --> ds_functions_scramble_bind
ds_functions_scramble --> ds_functions_scramble_meta
ds_functions_scramble --> ds_functions_scramble_panel
ds_functions_scramble_bind --> ds_functions_scramble_bind_refs
ds_functions_scramble_bind --> ds_functions_scramble_bind_sound
ds_functions_scramble_bind --> ds_functions_scramble_bind_ui
ds_functions_scramble_bind --> ds_functions_scramble_run
ds_functions_scramble_bind --> ds_functions_scramble_teardown
ds_functions_scramble_bind_sound --> views_element_sound
ds_functions_scramble_bind_sound --> views_slot_sound
ds_functions_scramble_bind_sound --> views_sound_source
ds_functions_scramble_code_tab --> ds_functions_views_scramble_text
ds_functions_scramble_code_tab --> ds_specimens
ds_functions_scramble_lab_sound --> ds_specimens
ds_functions_scramble_opts --> ds_functions_scramble_meta
ds_functions_scramble_opts --> views_sound_files
ds_functions_scramble_opts --> views_sound_source
ds_functions_scramble_panel --> ds_functions_scramble_code_tab
ds_functions_scramble_panel --> ds_functions_scramble_lab_sound
ds_functions_scramble_panel --> ds_functions_scramble_lab_text
ds_functions_scramble_panel --> ds_functions_scramble_opts
ds_functions_scramble_run --> ds_functions_scramble_meta
ds_functions_scramble_run --> views_scramble_text
ds_functions_scramble_run --> views_sound_source
ds_functions_shimmer --> ds_fx_lab
ds_functions_shimmer --> ds_specimens
ds_functions_viewer --> ds_specimens
ds_fx_lab --> ds_fx_lab_cells
ds_fx_lab --> ds_fx_lab_panels
ds_fx_lab_cells --> ds_fx_lab_cells_draw
ds_fx_lab_cells --> ds_fx_lab_cells_texture
ds_fx_lab_cells --> ds_fx_lab_color
ds_fx_lab_cells --> views_masonry_cells
ds_fx_lab_cells_draw --> ds_fx_lab_color
ds_fx_lab_cells_draw --> views_masonry_cells
ds_fx_lab_cells_texture --> ds_fx_lab_color
ds_fx_lab_cells_texture --> views_masonry_cells
ds_fx_lab_color --> ds_specimens
ds_fx_lab_color --> views_masonry_cells
ds_library_card --> ds_playground
ds_library_card --> ds_specimens
ds_library_contact --> ds_playground
ds_library_cta --> ds_playground
ds_library_filters --> ds_playground
ds_library_footer --> ds_playground
ds_library_header --> ds_playground
ds_library_hero --> ds_playground
ds_library_next --> ds_playground
ds_library_spec --> ds_playground
ds_library_spec --> ds_specimens
ds_library_strip --> ds_playground
ds_library_work --> ds_playground
ds_library_work --> ds_specimens
ds_overview_principles --> ds_specimens
ds_overview_reading --> ds_specimens
ds_overview_sections --> ds_overview_hero
ds_overview_sections --> ds_overview_mood
ds_overview_sections --> ds_overview_principles
ds_overview_sections --> ds_overview_reading
ds_overview_sections --> ds_overview_style_a
ds_overview_sections --> ds_overview_style_b
ds_pages_atlas --> ds_atlas_actions
ds_pages_atlas --> ds_atlas_camera
ds_pages_atlas --> ds_atlas_dock
ds_pages_atlas --> ds_atlas_fullscreen
ds_pages_atlas --> ds_atlas_insight
ds_pages_atlas --> ds_atlas_layout
ds_pages_atlas --> ds_atlas_schema
ds_pages_atlas --> ds_atlas_shell
ds_pages_atlas --> ds_atlas_tooltip
ds_pages_atlas --> ds_atlas_view
ds_pages_changelog --> ds_changelog_events
ds_pages_changelog --> ds_changelog_links
ds_pages_changelog --> ds_changelog_paint
ds_pages_changelog --> ds_changelog_parse
ds_pages_changelog --> ds_changelog_tags
ds_pages_changelog --> ds_changelog_titles
ds_pages_components --> ds_specimens
ds_pages_foundations --> ds_foundations_handlers
ds_pages_foundations --> ds_foundations_mix
ds_pages_foundations --> ds_foundations_pane_color
ds_pages_foundations --> ds_foundations_pane_contract
ds_pages_foundations --> ds_foundations_pane_fx
ds_pages_foundations --> ds_foundations_pane_motion
ds_pages_foundations --> ds_foundations_pane_shape
ds_pages_foundations --> ds_foundations_pane_space
ds_pages_foundations --> ds_foundations_pane_type
ds_pages_foundations --> ds_specimens
ds_pages_foundations --> ds_tabs
ds_pages_functions --> ds_specimens
ds_pages_library --> ds_library_card
ds_pages_library --> ds_library_contact
ds_pages_library --> ds_library_cta
ds_pages_library --> ds_library_filters
ds_pages_library --> ds_library_footer
ds_pages_library --> ds_library_header
ds_pages_library --> ds_library_hero
ds_pages_library --> ds_library_next
ds_pages_library --> ds_library_spec
ds_pages_library --> ds_library_strip
ds_pages_library --> ds_library_work
ds_pages_library --> ds_playground
ds_pages_library --> ds_specimens
ds_pages_overview --> ds_overview_sections
ds_pages_overview --> views_glimmer_orb
ds_pages_patterns --> ds_patterns_data
ds_pages_patterns --> ds_patterns_layouts
ds_pages_patterns --> ds_patterns_quality
ds_pages_primitives --> ds_component
ds_pages_primitives --> ds_primitives_avatar
ds_pages_primitives --> ds_primitives_badge
ds_pages_primitives --> ds_primitives_btn
ds_pages_primitives --> ds_primitives_divider
ds_pages_primitives --> ds_primitives_field
ds_pages_primitives --> ds_primitives_kicker
ds_pages_primitives --> ds_primitives_logo
ds_pages_primitives --> ds_primitives_tag
ds_pages_primitives --> ds_primitives_toggle
ds_pages_primitives --> ds_specimens
ds_patterns_data --> ds_specimens
ds_patterns_layouts --> ds_specimens
ds_patterns_quality --> ds_patterns_data
ds_patterns_quality --> ds_specimens
ds_playground --> ds_playground_knobs
ds_playground --> ds_specimens
ds_primitives_avatar --> ds_component
ds_primitives_badge --> ds_component
ds_primitives_btn --> ds_component
ds_primitives_divider --> ds_component
ds_primitives_field --> ds_component
ds_primitives_field --> ds_primitives_field_code
ds_primitives_field --> ds_primitives_field_meta
ds_primitives_kicker --> ds_component
ds_primitives_logo --> ds_component
ds_primitives_tag --> ds_component
ds_primitives_toggle --> ds_component
ds_routes --> ds_functions_glimmer_orb
ds_routes --> ds_functions_glitch
ds_routes --> ds_functions_grid_reveal
ds_routes --> ds_functions_rise
ds_routes --> ds_functions_scramble
ds_routes --> ds_functions_shimmer
ds_routes --> ds_functions_viewer
ds_routes --> ds_pages_atlas
ds_routes --> ds_pages_changelog
ds_routes --> ds_pages_components
ds_routes --> ds_pages_foundations
ds_routes --> ds_pages_functions
ds_routes --> ds_pages_library
ds_routes --> ds_pages_overview
ds_routes --> ds_pages_patterns
ds_routes --> ds_pages_primitives
ds_specimens --> ds_specimens_color
ds_specimens --> ds_specimens_copy
ds_specimens --> ds_specimens_grids
ds_specimens --> ds_specimens_markup
ds_specimens --> ds_specimens_trace
ds_specimens_copy --> ds_specimens_color
ds_specimens_grids --> ds_specimens_color
ds_specimens_trace --> ds_specimens_color
ds_specimens_trace --> ds_specimens_grids
ds_theme --> ds_specimens
fx_sound_index --> views_audio_ctx
fx_sound_index --> views_element_sound
fx_sound_index --> views_glitch_sound
fx_sound_index --> views_init_sound
fx_sound_index --> views_slot_sound
fx_sound_index --> views_sound_files
fx_sound_index --> views_sound_palette
fx_sound_index --> views_sound_source
fx_sound_voices_drone --> fx_sound_voices_helpers
fx_sound_voices_tone --> fx_sound_voices_helpers
fx_visual_index --> views_glimmer_orb
fx_visual_index --> views_glitch
fx_visual_index --> views_masonry_gridReveal
fx_visual_index --> views_rise
fx_visual_index --> views_scramble_text
fx_visual_index --> views_title_reveal
main --> boot_chrome
main --> theme
main --> views_contact
main --> views_headerFrame
main --> views_map_index
main --> views_masonry
main --> views_minimal_lab
main --> views_project
main --> views_settings_menu
main --> views_shared
views_audio_ctx --> views_audio_test
views_audio_test --> views_audio_ctx
views_contact --> data_site
views_contact --> views_rise
views_contact --> views_shared
views_contact --> views_title_reveal
views_element_sound --> views_audio_ctx
views_element_sound --> views_sound_files
views_element_sound --> views_sound_palette
views_glimmer_orb --> views_glimmer_color
views_glitch --> views_glitch_init
views_glitch_init --> views_glitch
views_glitch_sound --> views_audio_ctx
views_glitch_sound --> views_glitch_sound_geom
views_glitch_sound --> views_glitch_sound_parse
views_glitch_sound --> views_glitch_sound_timing
views_glitch_sound --> views_sound_palette
views_glitch_sound_parse --> views_sound_palette
views_glitch_sound_timing --> views_audio_ctx
views_init_sound --> views_glitch_sound
views_init_sound --> views_init_sound_load
views_init_sound --> views_strip_sound
views_init_sound_load --> views_audio_ctx
views_init_sound_load --> views_slot_sound
views_map_canvas --> views_map_data
views_map_canvas --> views_map_hits
views_map_canvas --> views_map_render
views_map_canvas --> views_map_wires
views_map_chunk --> views_map_geom
views_map_data --> views_map_focus
views_map_data --> views_map_geom
views_map_data --> views_map_store
views_map_drag --> views_map_data
views_map_drag --> views_map_route
views_map_focus --> views_map_store
views_map_hits --> views_map_data
views_map_hits --> views_map_route
views_map_index --> views_map_canvas
views_map_index --> views_map_data
views_map_index --> views_map_paint
views_map_index --> views_map_pointer
views_map_index --> views_map_route
views_map_index --> views_map_sound
views_map_index --> views_map_tips
views_map_index --> views_map_ui
views_map_pointer --> views_map_data
views_map_pointer --> views_map_drag
views_map_pointer --> views_map_popover
views_map_pointer --> views_map_route
views_map_popover --> views_map_data
views_map_render --> views_map_data
views_map_render --> views_map_paint
views_map_sound --> views_element_sound
views_map_store --> views_map_chunk
views_map_store --> views_map_geom
views_map_tips --> views_map_popover
views_map_ui --> views_map_data
views_map_ui --> views_map_store
views_map_wires --> views_map_data
views_map_wires --> views_map_paint
views_map_wires --> views_map_route
views_masonry --> data_site
views_masonry --> views_masonry_cards
views_masonry --> views_masonry_layout
views_masonry --> views_masonry_parallax
views_masonry --> views_masonry_reveal
views_masonry --> views_masonry_viewer
views_masonry --> views_shared
views_masonry --> views_title_reveal
views_masonry_cards --> views_img_helpers
views_masonry_cells --> views_masonry_cells_order
views_masonry_gridReveal --> views_masonry_cells
views_masonry_gridReveal --> views_masonry_gridReveal_config
views_masonry_gridReveal --> views_masonry_gridReveal_draw
views_masonry_gridReveal --> views_masonry_gridReveal_load
views_masonry_gridReveal --> views_masonry_gridReveal_tick
views_masonry_gridReveal_config --> views_fx_tokens
views_masonry_gridReveal_draw --> views_masonry_cells
views_masonry_gridReveal_load --> views_fx_tokens
views_masonry_gridReveal_load --> views_masonry_cells
views_masonry_gridReveal_tick --> views_masonry_cells
views_masonry_parallax --> views_masonry_parallax_calc
views_masonry_parallax --> views_masonry_parallax_chase
views_masonry_parallax --> views_masonry_parallax_measure
views_masonry_reveal --> views_fx_tokens
views_masonry_reveal --> views_masonry_gridReveal
views_masonry_viewer --> views_fx_tokens
views_masonry_viewer --> views_masonry_viewer_bind
views_masonry_viewer --> views_masonry_viewer_markup
views_masonry_viewer --> views_masonry_viewer_visibility
views_masonry_viewer_bind --> views_masonry_viewer_markup
views_minimal_lab --> views_map_data
views_minimal_lab --> views_shared
views_project --> data_site
views_project --> views_img_helpers
views_project --> views_rise
views_project --> views_shared
views_project --> views_title_reveal
views_rise --> views_fx_tokens
views_rise --> views_masonry_gridReveal
views_scramble_build --> views_scramble_helpers
views_scramble_text --> views_scramble_build
views_scramble_text --> views_scramble_helpers
views_shared --> data_site
views_slot_sound --> views_audio_ctx
views_slot_sound --> views_element_sound
views_slot_sound --> views_sound_source
views_sound_palette --> fx_sound_voices_drone
views_sound_palette --> fx_sound_voices_noise
views_sound_palette --> fx_sound_voices_scan
views_sound_palette --> fx_sound_voices_tone
views_strip_sound --> views_slot_sound
views_title_reveal --> views_scramble_text
views_title_reveal --> views_slot_sound
